# Generated by Django 5.2.15 on 2026-06-19 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_photo', models.ImageField(upload_to='invoices/%Y/%m/%d/', verbose_name='Фото накладной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время визита')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='catalog.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_qty', models.PositiveIntegerField(default=0, verbose_name='Отгружено')),
                ('expired_qty', models.PositiveIntegerField(default=0, verbose_name='Просрочка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='Товар')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='visits.visit', verbose_name='Визит')),
            ],
            options={
                'verbose_name': 'Строка визита',
                'verbose_name_plural': 'Строки визита',
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['manager', 'created_at'], name='visits_visi_manager_30c94d_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['created_at'], name='visits_visi_created_7580ca_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['store'], name='visits_visi_store_i_00757c_idx'),
        ),
        migrations.AddIndex(
            model_name='visititem',
            index=models.Index(fields=['product'], name='visits_visi_product_1535b6_idx'),
        ),
    ]
